version: '3.8'

services:
    mysql:
        image: mysql
        restart: unless-stopped
        ports:
            - ${DB_HOST}:3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./src/migrations/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - ${DB_HOST}:8081:80
        links:
            - mysql:db
        depends_on:
            - mysql
    web:
        image: nginx
        ports:
            - ${WEB_HOST}:8080:80
        restart: unless-stopped
        volumes:
            - ./src:/var/www
            - .:/etc/nginx/conf.d
        links:
            - php-app-starter
        depends_on:
            - php-app-starter
    php-app-starter:
        build:
          args:
            user: ${USER}
          context: .
          dockerfile: Dockerfile
        container_name: php-app-starter
        restart: unless-stopped
        volumes:
            - ./src:/var/www
volumes:
  mysql_data:
    driver: local